2023-10-20 13:55:08,541 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-20 13:55:28,783 ERROR: Exception on /edit_profile [POST] [in C:\CODING\python\microblog\env\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\CODING\python\microblog\env\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\app\routes.py", line 92, in edit_profile
    db.session.commit()
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1967, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1256, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1231, in _prepare_impl
    self.session.flush()
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4310, in flush
    self._flush(objects)
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4445, in _flush
    with util.safe_reraise():
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4406, in _flush
    flush_context.execute()
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 909, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1848, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\engine\base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "C:\CODING\python\microblog\env\Lib\site-packages\sqlalchemy\engine\default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('alex', 'Something about myself here', 3)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-10-20 13:59:26,420 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-26 15:54:55,480 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-26 16:21:24,174 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-26 16:21:34,530 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-26 16:52:29,440 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-26 17:09:58,185 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-27 10:04:20,304 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-27 10:35:09,713 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-27 10:37:17,543 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-27 10:45:23,069 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-27 10:47:23,842 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-27 10:47:56,796 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-30 13:04:21,573 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-30 13:04:53,986 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-30 13:12:44,254 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-10-30 13:17:38,029 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-11-08 17:59:25,909 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:49]
2023-12-06 13:57:57,713 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:54]
2023-12-06 13:58:13,954 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:54]
2023-12-06 13:58:39,862 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:54]
2023-12-06 14:08:45,281 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:54]
2023-12-06 14:15:49,706 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:54]
2023-12-06 14:17:06,876 INFO: Microblog startup [in C:\CODING\python\microblog\app\__init__.py:54]
